[project]
name = "r2da"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.1",
    "opencv-python>=4.13.0.90",
    "pdf2image>=1.17.0",
    "pillow>=12.1.0",
]
